---
deployment:
  tasks:
    - export DEPLOYPATH=/home/thalwyas/staging.thaliaventuris.com/
    - /bin/cp -R index.html Growth Contacts News-and-Insights At-a-Glance assets contact-handler.php $DEPLOYPATH
